services:
- postgresql
language: ruby
rvm:
- 2.3.1
env:
- DB=postgresql
before_script:
- psql -c 'create database ar_teams_and_leagues_challenge_rails_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec/
deploy:
  provider: heroku
  app: frightening-moonlight-10587
  api_key:
    secure: Lxaskn1nYdh1JSejxZ27obnJSvNYHUzE/Gi3Z0y2iAiKRISFnQY5znytBrDKybhaLzjDuIl8qrxq/m430lhizcNJUrAY8F9dKISPUbcsJcjqM0ZDVAdTqKj25wXIwbFtfvzYCqtLqUhT1aa6fjdp165xVT73hyNgxB+ToHP+VkbGZXEcn+/c+bRj9H776x2R5gNwpHFxjOeW0Ju6lQZnnXnA76TBW+4LM/VfnLErgAJqJlsywhF3IBl43PHy2bYGpX6jmdcQXUUzP01RE0ZgKZoX24tQbHaqA4+mVKjySXWgw530MYwNdw1bsgBIDybWS0t3up9ReKVXb1JxclUapR/schfcLIhQXW5mRzUT+pWuLm2dwFPd9k6V2xrKb8o1SJ83VB/pPn7G1AvXQbejTo1q0uQsFO7iude2caurI/OC0Q8kDKLH9dDzl4Tr98dAL+5ykpAHQe5un5cxsCKAby7cbBABMTVAEJQ7NLRnoF+wQHVzTEnR8hAYwSV4p6d910PoaHP4XD5RcEDD//f0+rSyCFdA4W8mGM4I7HcaNzrcwpO4o6fKtseJXrRAR+pk2bz4CiUOqSvRHxkCrizPJelUZjn6xbCithwbkja5WfWvMTJl8CNduTMIXUUgK2RehnQGH9/qjvJi2RCn0RKOqliIAdCNKawbXplu54q49zA=
